## Rule index for SCDC deconv
##
## @zgr2788
## @SciLiciumTheo
##
##
## Description:
## This file includes the rule to run SCDC with C0 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##


rule SCDC_install:
    input:
    output:
        touch("Modules/SCDC/SCDC_installed.done")
    conda:
        "env.yaml"
    shell:
        """
            Rscript -e "devtools::install_github('meichendong/SCDC')"
        """


rule SCDC_run:
    input:
        installed = "Modules/SCDC/SCDC_installed.done",
        phendata = getPhenData(getC0(getBulks('{sample}'), '{sample}'), '{sample}')

    output:
        "Output/{sample}_res_SCDC.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_SCDC_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['SCDC'])

    shell:
        "Rscript Modules/SCDC/SCDC_run.R {input.phendata} {output}"
