## Rule index for MuSiC deconv
##
## @zgr2788
## @SciliciumTheo
##
##
## Description:
## This file includes the rule to run MuSiC with C0 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule MuSiC_install:
    input:
    output:
        touch("MuSiC_installed.done")
    conda:
        "env.yaml"
    shell:
        """
            Rscript -e "devtools::install_github('xuranw/MuSiC')"
        """

rule MuSiC_run:
    input:
        installed = "MuSiC_installed.done",
        phendata = getPhenData(getC0(getBulks('{sample}'), '{sample}'), '{sample}')

    output:
        "Output/{sample}_res_MuSiC.rds"

    conda:
        "env.yaml"

    params:
        forceRaw = config['forceMuSiCRaw']

    benchmark:
        "Benchmarks/{sample}_MuSiC_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['MuSiC'])

    shell:
        "Rscript Modules/MuSiC/MuSiC_run.R {input.phendata} {params} {output}"
